### ISSUE TITLE
Dot files not sorted

### ISSUE THREAD

**Issue by gene-pavlovsky** [rockandska/fzf-obc#37]
default.cfg:
```
std_sort_opts='-V'
std_filedir_hidden_first='0'
```

Dot files are shown after regular files, as expected.
Regular files are sorted as expected.
Dot files, however, appear to be unsorted.

Screenshot: 
<img width="214" alt="Screenshot 2020-01-23 at 16 13 00" src="https://user-images.githubusercontent.com/2841193/72996658-5fb4ee00-3dfb-11ea-910e-96d1490870fd.png">

**Comment by rockandska** [comment]
Hi @gene-pavlovsky ,

In fact, after some tests, this bug seems directly related to the use of `-V` options without using `-d`.

No sort options, the results is ok
```shell
$ listing=("/etc/" "/home/" "/opt/" "/private/" "/sbin/" "/tmp/" "/usr/" "/var/" "/.VolumeIcon.icns" "/.file" "/.DS_Store" "/.fseventsd/" "/.vol/")
$ printf '%s\0' "${listing[@]}" | current_cmd_name=test current_sort_opts='' __fzf_obc_sort | __fzf_obc_move_hidden_files_last | tr '\0' '\n'
/etc/
/home/
/opt/
/private/
/sbin/
/tmp/
/usr/
/var/
/.DS_Store
/.VolumeIcon.icns
/.file
/.fseventsd/
/.vol/
```

Using only `-V`, the result is the same as you described
```shell
$ printf '%s\0' "${listing[@]}" | current_cmd_name=test current_sort_opts='-V' __fzf_obc_sort | __fzf_obc_move_hidden_files_last | tr '\0' '\n'
/etc/
/home/
/opt/
/private/
/sbin/
/tmp/
/usr/
/var/
/.VolumeIcon.icns
/.file
/.DS_Store
/.fseventsd/
/.vol/
```

Using `-Vd` the result is ok
```shell
printf '%s\0' "${listing[@]}" | current_cmd_name=test current_sort_opts='-Vd' __fzf_obc_sort | __fzf_obc_move_hidden_files_last | tr '\0' '\n'
/etc/
/home/
/opt/
/private/
/sbin/
/tmp/
/usr/
/var/
/.DS_Store
/.VolumeIcon.icns
/.file
/.fseventsd/
/.vol/
```

I think i will set sort_opts to "" in the next release.

Could you test by setting std_sort_opts to "" or "-Vd" and close this issue if it works as you would like ?

Regards,

**Comment by gene-pavlovsky** [comment]
Indeed, "-Vd" produces the results you mentioned. I wonder why is that option necessary...
Thanks for looking into this.

**Comment by rockandska** [comment]
In fact, i'm thinking that using options as `-V -i -d` is the real problem here and will be best to use them only in precise context.
This is for the same reason i will set sort_opts="" in next release.

In my previous example with `-Vd`, the result is correct because you use `std_filedir_hidden_first='0'`.
If you don't use it, since `-d` ignore non alphanumeric, you will see that the order is not the one expected
```
$ printf '%s\0' "${listing[@]}" | LC_ALL=C sort -z | tr '\0' '\n'
/.DS_Store
/.VolumeIcon.icns
/.file
/.fseventsd/
/.vol/
/etc/
/home/
/opt/
/private/
/sbin/
/tmp/
/usr/
/var/
$ printf '%s\0' "${listing[@]}" | LC_ALL=C sort -z -V | tr '\0' '\n'
/.VolumeIcon.icns
/.file
/etc/
/home/
/opt/
/private/
/sbin/
/tmp/
/usr/
/var/
/.DS_Store
/.fseventsd/
/.vol/
$ printf '%s\0' "${listing[@]}" | LC_ALL=C sort -z -Vd | tr '\0' '\n'
/.DS_Store
/.VolumeIcon.icns
/etc/
/.file
/.fseventsd/
/home/
/opt/
/private/
/sbin/
/tmp/
/usr/
/var/
/.vol/
```
