### ISSUE TITLE
(question) help with bindings.

### ISSUE THREAD

**Issue by nerd190** [rockandska/fzf-obc#44]
Thank you, this is amazing!
I have tried to configure bindings as shown via the wiki page but have been unsuccessful.
Most importantly:
- I would like 'tab' to cycle through the entries just like normal bash does instead of its current behaviour (nothing or toggling multiple selections), if not can it be mapped as 'down' instead?

Also:
- Can D-pad 'left' & 'right' be mapped? I'd love to map the to 'up' & 'down'.
- Can 'control' be mapped?
- Have 'multiple' & 'recursive' selections shown as default without `*` or `**` before tab?

Thank you again, its really appreciated! amazing work!!

**Comment by rockandska** [comment]
> Thank you, this is amazing!

Thanks

> I would like 'tab' to cycle through the entries just like normal bash does instead of its current behaviour (nothing or toggling multiple selections), if not can it be mapped as 'down' instead?

The bindings are the one accepted by fzf itself.
You could bind Tab to `down` but it seems not possible to circle over the results with fzf (open a FR on fzf repository if you would find it helpful)

> Can D-pad 'left' & 'right' be mapped? I'd love to map the to 'up' & 'down'.
> Can 'control' be mapped?

All those questions have answer in the manpage of fzf

As a an example :

```
$ cat > $HOME/.config/fzf-obc/default.cfg
std_fzf_binds='--bind left:toggle --bind right:accept'
mlt_fzf_binds='--bind left:toggle --bind right:accept'
```
Will let you press `left arrow` to select an entry (when in multi selection mode) and validate when pressing `right arrow` key

```shell
$ cat > $HOME/.config/fzf-obc/default.cfg
std_fzf_trigger='**'        
mlt_fzf_trigger='*'
rec_fzf_trigger=''
```

> Have 'multiple' & 'recursive' selections shown as default without * or ** before tab?

```shell
$ cat > $HOME/.config/fzf-obc/default.cfg
std_fzf_trigger='**'        
mlt_fzf_trigger='*'
rec_fzf_trigger=''
```
but i will not recommend this configuration because it will hang for ever when you will be in a top directory with many subfolders / files like "/"

Regards,

**Comment by rockandska** [comment]
Never had feedback.

Please reopen if needed
